# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbflow',
                'doc_host': 'https://threefoldo.github.io',
                'git_url': 'https://github.com/threefoldo/nbflow',
                'lib_path': 'nbflow'},
  'syms': {'nbflow.core': {'nbflow.core.foo': ('core.html#foo', 'nbflow/core.py')}}}
